java_exp3.1/src/cn/edu/hactcm/domain/Cart.java
package cn.edu.hactcm.domain;

import org.apache.commons.collections.map.HashedMap;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

public class Cart {
    private Map <String, CartItem> itemMap = new HashMap <String, CartItem>();
    private Double total=0.0;

    public Map <String, CartItem> getItemMap() {
        return itemMap;
    }

    public void setItemMap(Map <String, CartItem> itemMap) {
        this.itemMap = itemMap;
    }

    public Double getTotal() {
        return total;
    }

    public void setTotal(Double total) {
        this.total = total;
    }

    /**
     * 加入购物车
     */
    public void addToCart(CartItem item) {

        String pid = item.getProduct().getPid();
        //判断购物车中是否有
        if (itemMap.containsKey(pid)) {
            //有 修改数量

            //原来的购物项
            CartItem cartItem = itemMap.get(pid);
            cartItem.setCount(cartItem.getCount()+item.getCount());
        }else {
            itemMap.put(pid,item);

        }
        //修改总金额
        total+=item.getSubtotal();
    }

    /**
     * 加入购物车
     */
    public void removeFromCart(String pid) {

        //从购物车（map）中移除 购物项
        CartItem item = itemMap.remove(pid);
        //修改总金额
        total-=item.getSubtotal();

    }

    /**
     * 加入购物车
     */
    public void ClearCart() {
        //清空map集合
        itemMap.clear();
        //修改总金额
        total=0.0;
    }

    /**
     * 获取所有的购物项（就是map集合中所有的value值）
     */
    public Collection<CartItem> getCartItems(){
        return itemMap.values();
    }
}

java_exp3.1/src/cn/edu/hactcm/Web/Servlet/CartServlet.java
package cn.edu.hactcm.Web.Servlet;

import cn.edu.hactcm.Service.ProductService;
import cn.edu.hactcm.Util.BeanFactory2;
import cn.edu.hactcm.Web.Servlet.Base.BaseServlet;
import cn.edu.hactcm.domain.Cart;
import cn.edu.hactcm.domain.CartItem;
import cn.edu.hactcm.domain.Product;
import cn.edu.hactcm.domain.user;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
/*
购物车是一次性的，再次登陆已经没有了，是因为：程序他购物车存在Session里面
 */
@WebServlet("/CartServlet")
public class CartServlet extends BaseServlet {
    /**
     * 添加到购物车
     * @param req
     * @param resp
     * @return
     */
    public String addToCart(HttpServletRequest req, HttpServletResponse resp) {
        try {
            user user1 = (user) req.getSession().getAttribute("user");
            if (user1 == null) {
                req.setAttribute("msg", "请先登录！");
                return "/jsp/msg.jsp";
            }

            //获取pid，count
            String pid = req.getParameter("pid");
            int count = Integer.parseInt(req.getParameter("count"));

            //工厂实例化一个productService对象
            ProductService productService = (ProductService) BeanFactory2.getBean("ProductService");
            //查询pid对象的商品信息
            Product product = productService.getById(pid);

            //创建商品项（CartItem）
            CartItem cartItem = new CartItem(product, count);

            //将商品项加入购物车（Cart）
            //获取购物车
            Cart cart = getCart(req);
            cart.addToCart(cartItem);
            resp.sendRedirect(req.getContextPath()+"/jsp/Cart.jsp");
        } catch (Exception e) {
            e.printStackTrace();
            req.setAttribute("msg","加入购物车失败");
            return "/jsp/msg.jsp";
        }
        return null;
    }

    /**
     * 获取购物车方法
     * @param req
     * @return
     */
    private Cart getCart(HttpServletRequest req) {
        Cart cart= (Cart)req.getSession().getAttribute("cart");
        if (cart == null) {
            cart=new Cart();

            req.getSession().setAttribute("cart",cart);
        }
        return cart;

    }

    public String showCart(HttpServletRequest req, HttpServletResponse resp){
        user user1 = (user) req.getSession().getAttribute("user");
        if (user1 == null) {
            req.setAttribute("msg", "请先登录！");
            return "/jsp/msg.jsp";
        }
        try {
            resp.sendRedirect(req.getContextPath()+"/jsp/Cart.jsp");
        } catch (IOException e) {
            e.printStackTrace();
            req.setAttribute("msg","查询失败");
            return "/jsp/msg.jsp";
        }
        return null;

    }
    /**
     * 删除购物项从购物车里面
     */
    public String remove(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        //获取商品的pid
        String pid = req.getParameter("pid");
        //获取购物车，执行移除
        getCart(req).removeFromCart(pid);
        //重定向
        resp.sendRedirect(req.getContextPath()+"/jsp/Cart.jsp");
        return null;
    }
    /**
     * 清空购物车
     */
    public String clear(HttpServletRequest req, HttpServletResponse resp) throws IOException {

        //获取购物车，执行移除
        getCart(req).ClearCart();
        //重定向
        resp.sendRedirect(req.getContextPath()+"/jsp/Cart.jsp");
        return null;
    }
}

java_exp3.1/web/jsp/404.jsp
<%--
  Created by IntelliJ IDEA.
  User: wangshibo
  Date: 2020/4/15
  Time: 12:38
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Title</title>
</head>
<body>
请检查的你的访问路径，功能暂时还没有开发出来
</body>
</html>

java_exp3.1/web/jsp/500.jsp
<%--
  Created by IntelliJ IDEA.
  User: wangshibo
  Date: 2020/4/15
  Time: 12:38
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Title</title>
</head>
<body>
不好意思，内部错误
</body>
</html>

java_exp3.1/web/jsp/Cart.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%--
  Created by IntelliJ IDEA.
  User: wangshibo
  Date: 2020/4/19
  Time: 10:42
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="author" content="order by dede58.com"/>
    <title>我的购物车-xueyuan商城</title>
    <link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/css/style.css">
    <script src="http://libs.baidu.com/jquery/2.1.4/jquery.min.js"></script>
</head>
<body>
<!-- start header -->
<%@include file="head.jsp"%>
<!-- start banner_x -->

<div class="xiantiao"></div>

<div class="gwcxqbj">
    <div class="gwcxd center">
        <c:if test="${empty cart||empty cart.cartItems}">
            <h4>购物车空空如也，请先去逛逛去吧.........</h4>
        </c:if>
        <c:if test="${not empty cart.cartItems}">
        <%--标题栏--%>
        <div class="top2 center">
            <div class="sub_top fl">
                <%--<input type="checkbox" value="quanxuan" class="quanxuan" />全选--%>
            </div>
            <div class="sub_top fl">商品名称</div>
            <div class="sub_top fl">单价</div>
            <div class="sub_top fl">数量</div>
            <div class="sub_top fl">小计</div>
            <div class="sub_top fr">操作</div>
            <div class="clear"></div>
        </div>

        <c:forEach items="${cart.cartItems}" var="ci">

            <div class="content2 center">
                <div class="sub_content fl ">
                    <%--<input type="checkbox" value="quanxuan" class="quanxuan" />--%>
                </div>
                <div class="sub_content fl"><img src="<%=request.getContextPath()%>${ci.product.pimage}"></div>
                <div class="sub_content fl ft20">${ci.product.pname}</div>
                <div class="sub_content fl ">${ci.product.shop_price}</div>
                <div class="sub_content fl">
                    <input class="shuliang" readonly type="number" value="${ci.count}" step="1" min="1" >
                </div>
                <div class="sub_content fl">${ci.subtotal}</div>
                <div class="sub_content fl"><a href="javascript:void(0)" onclick="removeFromCart('${ci.product.pid}')">×</a></div>
                <div class="clear"></div>
            </div>

        </c:forEach>
        </c:if>
    </div>

    <div class="jiesuandan mt20 center">
        <div class="tishi fl ml20">
            <ul>
                <li><a href="<%=request.getContextPath()%>/CartServlet?method=clear">清空购物车</a></li>
                <%--<li>|</li>--%>
                <%--<li>共<span>2</span>件商品，已选择<span>1</span>件</li>--%>
                <div class="clear"></div>
            </ul>
        </div>
        <div class="jiesuan fr">
            <div class="jiesuanjiage fl">合计（不含运费）：<span>${cart.total}元</span></div>
            <div class="jsanniu fr"><input class="jsan" type="button" onclick="orderGenerate()" name="jiesuan"  value="去下单"/></div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>

</div>




<!-- footer -->
<footer class="center">

    <div class="mt20">小米商城|MIUI|米聊|多看书城|小米路由器|视频电话|小米天猫店|小米淘宝直营店|小米网盟|小米移动|隐私政策|Select Region</div>
    <div>©mi.com 京ICP证110507号 京ICP备10046444号 京公网安备11010802020134号 京网文[2014]0059-0009号</div>
    <div>违法和不良信息举报电话：185-0130-1238，本网站所列数据，除特殊说明，所有数据均出自我司实验室测试</div>
</footer>

</body>
<script type="text/javascript">
    function removeFromCart(pid) {
        if (confirm("你忍心抛弃我吗")) {
            var pathName=window.document.location.pathname;
            var projectName=pathName.substring(0,pathName.substr(1).indexOf('/')+1);
            location.href=projectName+"/CartServlet?method=remove&pid="+pid;
        }

    }

    function orderGenerate() {
        //pathName的值：例：/项目名/目录....
        var pathName=window.document.location.pathname;

        //截取项目的根目录
        var projectName=pathName.substring(0,pathName.substr(1).indexOf('/')+1);
        location.href= projectName+"/OrderServlet?method=save"

    }
</script>

</html>

java_exp3.1/web/jsp/head.jsp
<%--
  Created by IntelliJ IDEA.
  User: wangshibo
  Date: 2020/4/17
  Time: 11:26
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!-- start header -->
<header>
    <div class="top center">
        <div class="left fl">
            <ul>
                <li><a href="http://www.mi.com/" target="_blank">xueyuan商城</a></li>
                <li>|</li>
                <li><a href="">MIUI</a></li>
                <li>|</li>
                <li><a href="">米聊</a></li>
                <li>|</li>
                <li><a href="">游戏</a></li>
                <li>|</li>
                <li><a href="">多看阅读</a></li>
                <li>|</li>
                <li><a href="">云服务</a></li>
                <li>|</li>
                <li><a href="">金融</a></li>
                <li>|</li>
                <li><a href="">小米商城移动版</a></li>
                <li>|</li>
                <li><a href="">问题反馈</a></li>
                <li>|</li>
                <li><a href="">Select Region</a></li>
                <div class="clear"></div>
            </ul>
        </div>
        <div class="right fr">
            <div class="gouwuche fr"><a href="<%=request.getContextPath()%>/CartServlet?method=showCart">购物车</a></div>
            <div class="fr">
                <ul>
                    <c:if test="${empty user}">
                        <li><a href="<%=request.getContextPath()%>/userServlet?method=loginUI">登录</a></li>
                        <li>|</li>
                        <li><a href="<%=request.getContextPath()%>/userServlet?method=regeditUI">注册</a></li>
                    </c:if>
                    <c:if test="${not empty user}">
                        <li>${user.name}:你好</li>
                        <li><a href="<%=request.getContextPath()%>/OrderServlet?method=findMyOrderGetByPage&pageNumber=1">我的订单</a></li>
                        <li>|</li>
                        <li><a href="<%=request.getContextPath()%>/userServlet?method=logout">退出</a></li>
                    </c:if>

                    <li>|</li>
                    <li><a href="javascript:void(0)">消息通知</a></li>
                </ul>
            </div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
</header>
<!--end header -->

<!-- start banner_x -->
<div class="banner_x center">
    <a href="<%=request.getContextPath()%>/index2.html"><div class="logo fl"></div></a>

    <div class="nav fl">
        <ul id="c_ul">
            <li><a href="<%=request.getContextPath()%>/index2.jsp">首页</a></li>
        </ul>
    </div>
    <div class="search fr">
        <form action="" method="post">
            <div class="text fl">
                <input type="text" class="shuru"  placeholder="小米6&nbsp;小米MIX现货">
            </div>
            <div class="submit fl">
                <input type="submit" class="sousuo" value="搜索"/>
            </div>
            <div class="clear"></div>
        </form>
        <div class="clear"></div>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        //JQuery操作
        //请求的页面
        $.post("${pageContext.request.contextPath}/categoryServlet", {"method": "findAll"},
            function (obj) {
            //alert(obj)
                //遍历json列表，获取每一个分类，包装成li标签，插入到ul内部
                $(obj).each(function () {
                    //alert(this.cname);
                    $("#c_ul").append("<li><a href='${pageContext.request.contextPath}/ProductServlet?method=findByPage&pageNumber=1&cid="+this.cid+"'>"+this.cname+"</a></li>")

                });

            },"json");

    });
</script>

java_exp3.1/web/jsp/login_jsp.jsp
<%--
  Created by IntelliJ IDEA.
  User: wangshibo
  Date: 2020/2/21
  Time: 17:34
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="author" content="order by dede58.com"/>
    <title>会员登录</title>
    <link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/css/login.css">

</head>
<body>
<!-- login -->
<div class="top center">
    <div class="logo center">
        <a href="<%=request.getContextPath()%>/index.html" target="_blank"><img src="<%=request.getContextPath()%>/image/mistore_logo.png" alt=""></a>
    </div>
</div>
<form  method="post" action="<%=request.getContextPath()%>/userServlet" class="form center">
    <div class="login">
        <div class="login_center">
            <div class="login_top">
                <input type="hidden" name="method" value="login">
                <div class="left fl">会员登录</div>
                <div class="right fr">您还不是我们的会员？<a href="<%=request.getContextPath()%>/userServlet?method=regeditUI" target="_self">立即注册</a></div>
                <div class="clear"></div>
                <div class="xian center"></div>
            </div>
            <div class="login_main center">
                <div class="username">用户名:&nbsp;<input class="shurukuang" type="text" name="username" placeholder="请输入用户名或者邮箱"/></div>
                <div class="username">密&nbsp;&nbsp;&nbsp;&nbsp;码:&nbsp;<input class="shurukuang" type="password" name="password" placeholder="请输入你的密码"/></div>
                <div class="username">
                    <div class="left fl">验证码:&nbsp;<input class="yanzhengma" type="text" name="username" placeholder="请输入验证码"/></div>
                    <div class="right fl"><img src="<%=request.getContextPath()%>/image/yanzhengma.jpg"></div>
                    <div class="clear"></div>
                </div>
                <span style="color: red">${msg}</span>
            </div>
            <div class="login_submit">
                <input class="submit" type="submit" name="submit" value="立即登录" >
            </div>

        </div>
    </div>
</form>
<footer>
    <div class="copyright">简体 | 繁体 | English | 常见问题</div>
    <div class="copyright">小米公司版权所有-京ICP备10046444-<img src="<%=request.getContextPath()%>/image/ghs.png" alt="">京公网安备11010802020134号-京ICP证110507号</div>

</footer>
</body>
</html>

java_exp3.1/web/jsp/msg.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%--
  Created by IntelliJ IDEA.
  User: wangshibo
  Date: 2020/4/16
  Time: 14:41
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="author" content="order by dede58.com"/>
    <title>信息提示</title>
    <link rel="stylesheet" type="text/css" href="./css/style.css">
    <script src="http://libs.baidu.com/jquery/2.1.4/jquery.min.js"></script>
</head>
<body>
<!-- start header -->
<%@include file="head.jsp"%>


<!-- end banner_x -->
<!-- self_info -->
<div class="grzxbj">
    <div class="selfinfo center">
        <h4>${msg}</h4>
        <div class="clear"></div>
    </div>
</div>

<!-- self_info -->

<footer class="mt20 center">
    <div class="mt20">小米商城|MIUI|米聊|多看书城|小米路由器|视频电话|小米天猫店|小米淘宝直营店|小米网盟|小米移动|隐私政策|Select Region</div>
    <div>©mi.com 京ICP证110507号 京ICP备10046444号 京公网安备4号 京网文[2014]0059-0009号</div>
    <div>违法和不良信息举报电话：，本网站所列数据，除特殊说明，所有数据均出自我司实验室测试</div>
</footer>
</body>
</html>

java_exp3.1/web/jsp/order_info.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="f" uri="http://java.sun.com/jsp/jstl/functions" %>
<%--
  Created by IntelliJ IDEA.
  User: wangshibo
  Date: 2020/4/19
  Time: 21:34
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/css/style.css">
    <script src="http://libs.baidu.com/jquery/2.1.4/jquery.min.js"></script>

</head>
<body>
<%@include file="head.jsp"%>
<div class="xiantiao"></div>
<div class="gwcxqbj" style="height: auto;">

    <div class="gwcxd center">

        <div class="top2 center">
            &nbsp;订单编号：${bean.oid}
        </div>
            <%--标题栏--%>
            <div class="top2 center" style="height: 44px;height: 44px;">
                <div class="sub_top fl" style="width: 50px;height: 44px;"></div>
                <div class="sub_top fl" style="margin-left: 50px;height: 44px;">商品名称</div>
                <div class="sub_top fl" style="height: 44px">单价</div>
                <div class="sub_top fl"  style="height: 44px">数量</div>
                <div class="sub_top fl" style="width: 200px;height: 44px;">小计</div>
                <div class="sub_top fl"  style="height: 44px"></div>


                <div class="clear"></div>
            </div>

            <c:forEach items="${bean.items}" var="ci">

                <div class="content2 center" style="height: 100px">
                    <div class="sub_top fl" style="height: 100px"></div>
                    <div class="sub_content fl" style="height: 100px"><img src="<%=request.getContextPath()%>${ci.product.pimage}" style="margin: 3% auto;"></div>
                    <div class="sub_content fl ft20" style="margin-top:-1%;height: 100px">${ci.product.pname}</div>
                    <div class="sub_content fl " style="margin-top:-1%;height: 100px">${ci.product.shop_price}</div>
                    <div class="sub_content fl" style="margin-top:-1%;height: 100px">
                        <input class="shuliang" readonly type="number" value="${ci.count}" step="1" min="1" >
                    </div>
                    <div class="sub_content fl" style="margin-top:-1%;height: 100px">${ci.subtotal}</div>
                    <div class="sub_top fl"></div>
                    <div class="clear"></div>
                </div>

            </c:forEach>
    </div>

    <div class="jiesuandan mt20 center" style="margin-top: 2px">

        <div class="jiesuan fr">
            <div class="jiesuanjiage fl">合计（不含运费）：<span>${bean.total}元</span></div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>

    <div class="jiesuandan mt20 center" style="display: grid;height: 200px;">

        <div class="jiesuan fr">
            &nbsp;　　收&nbsp;&nbsp;件&nbsp;&nbsp;人：<input type="text">
        </div>
        <div class="jiesuan fr">
            &nbsp;　　联系电话：<input type="text">
        </div>
        <div class="jiesuan fr">
            &nbsp;　　收件地址：<input type="text">
        </div>
        <div class="clear"></div>
    </div>

</div>


<footer class="center">

    <div class="mt20">小米商城|MIUI|米聊|多看书城|小米路由器|视频电话|小米天猫店|小米淘宝直营店|小米网盟|小米移动|隐私政策|Select Region</div>
    <div>©mi.com 京ICP证110507号 京ICP备10046444号 京公网安备11010802020134号 京网文[2014]0059-0009号</div>
    <div>违法和不良信息举报电话：185-0130-1238，本网站所列数据，除特殊说明，所有数据均出自我司实验室测试</div>
</footer>
</body>
</html>

java_exp3.1/web/jsp/order_list.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%--
  Created by IntelliJ IDEA.
  User: wangshibo
  Date: 2020/4/20
  Time: 13:59
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="author" content="order by dede58.com"/>
    <title>我的订单-xueyuan商城</title>
    <link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/css/style.css">
    <script src="http://libs.baidu.com/jquery/2.1.4/jquery.min.js"></script>
</head>
<body>
<!-- start header -->
<%@include file="head.jsp"%>
<!--end header -->
<!-- start banner_x -->
<c:forEach items="${pb.data}" var="o">

<div class="gwcxqbj" style="height: auto;">
    <div class="gwcxd center">
        <%--宽度1226px--%>
        <div class="top2 center" style="width: 1226px;">

            <div class="sub_top fl" style="width:250px;height: 40px; "> &nbsp;订单编号：${o.oid}</div>
            <div class="sub_top fl" style="width:100px;height: 40px; ">
                <c:if test="${o.state==0}"><a href="<%=request.getContextPath()%>/OrderServlet?method=getOrderById&oid=${o.oid}">去付款</a></c:if>
                <c:if test="${o.state==1}">已付款</c:if>
                <c:if test="${o.state==2}">确认收货</c:if>
                <c:if test="${o.state==3}">已完成</c:if>
            </div>
            <div class="sub_top fl" style="width:216px;height: 40px; margin-left: 200px;"> ${o.ordertime}</div>
        </div>
        <%--标题栏--%>
        <div class="top2 center" style="height: 44px;height: 44px;">
            <div class="sub_top fl" style="width: 50px;height: 44px;"></div>
            <div class="sub_top fl" style="margin-left: 50px;height: 44px;">商品名称</div>
            <div class="sub_top fl" style="height: 44px">单价</div>
            <div class="sub_top fl"  style="height: 44px">数量</div>
            <div class="sub_top fl" style="width: 200px;height: 44px;">小计</div>
            <div class="sub_top fl"  style="height: 44px"></div>


            <div class="clear"></div>
        </div>

        <c:forEach items="${o.items}" var="oi">

            <div class="content2 center" style="height: 100px">
                <div class="sub_top fl" style="height: 100px"></div>
                <div class="sub_content fl" style="height: 100px"><img src="<%=request.getContextPath()%>${oi.product.pimage}" style="margin: 3% auto;"></div>
                <div class="sub_content fl ft20" style="margin-top:-1%;height: 100px">${oi.product.pname}</div>
                <div class="sub_content fl " style="margin-top:-1%;height: 100px">${oi.product.shop_price}</div>
                <div class="sub_content fl" style="margin-top:-1%;height: 100px">
                    <input class="shuliang" readonly type="number" value="${oi.count}" step="1" min="1" >
                </div>
                <div class="sub_content fl" style="margin-top:-1%;height: 100px">${oi.subtotal}</div>
                <div class="sub_top fl"></div>
                <div class="clear"></div>
            </div>

        </c:forEach>
    </div>

    <div class="jiesuandan mt20 center" style="margin-top: 2px">

        <div class="jiesuan fr">
            <div class="jiesuanjiage fl">合计（不含运费）：<span>${o.total}元</span></div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>

</div>
</c:forEach>


<%--分页--%>
<div class="main center mb20">
    <p align="center">

        <c:if test="${pb.pageNumber>1}">
            <a href="<%=request.getContextPath()%>/OrderServlet?method=findMyOrderGetByPage&pageNumber=1" >首页</a>
            <a href="<%=request.getContextPath()%>/OrderServlet?method=findMyOrderGetByPage&pageNumber=${pb.pageNumber-1}">上一页</a>
        </c:if>
        <c:if test="${pb.pageNumber<pb.totalPage}">
            <a href="<%=request.getContextPath()%>/OrderServlet?method=findMyOrderGetByPage&pageNumber=${pb.pageNumber+1}">下一页</a>
            <a href="<%=request.getContextPath()%>/OrderServlet?method=findMyOrderGetByPage&pageNumber=${pb.totalPage}">末页</a>
        </c:if>

    </p>
    <form action="<%=request.getContextPath()%>/OrderServlet?method=findMyOrderGetByPage" method="post">
        <h4 align="center" style="display: block">
            共${pb.totalPage}页
            <input type="number" style="border: 1px solid saddlebrown;" value="${pb.pageNumber}" min="1" max="${pb.totalPage}"  name="pageNumber" size="1">页
            <input type="submit" value="到达">
        </h4>
    </form>

</div>


<footer class="mt20 center">
    <div class="mt20">小米商城|MIUI|米聊|多看书城|小米路由器|视频电话|小米天猫店|小米淘宝直营店|小米网盟|小米移动|隐私政策|Select Region</div>
    <div>©mi.com 京ICP证110507号 京ICP备10046444号 京公网安备11010802020134号 京网文[2014]0059-0009号</div>
    <div>违法和不良信息举报电话：185-0130-1238，本网站所列数据，除特殊说明，所有数据均出自我司实验室测试</div>
</footer>
</body>
</html>